### ISSUE TITLE
problems defining a folder system and redirecting

### ISSUE THREAD

**Issue by pjg711** [bramus/router#100]
Hi.
I have problems defining a folder system and redirecting it to a folder called src and then accessing some of the defined paths. The "HTTP ERROR 404" error appears. I am using Router Bramus. For example:
/ application- |
.....................|- .htaccess (*)
.....................|- /tests
.....................|- /src - |
.................................|-.htaccess (**)
.................................|-/controllers
.................................|-/routers
.................................|-/models
.................................|-/views
-------------------------------------------
(\*) .htaccess 
RewriteEngine on
RewriteCond %{HTTP_HOST} ^localhost$ [NC,OR]
RewriteCond %{HTTP_HOST} ^localhost$
RewriteCond %{REQUEST_URI} !src/
RewriteRule (.*) src/$1 [L]

(**) .htaccess
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]

**Comment by bramus** [comment]
You need to place your `.htaccess` and `index.php` file in a the folder (typically named `public_html` or `default_www`) that is being served by Apache. This folder is typically on the same level as the `test` and `src` folder you have in your folder structure.
