### ISSUE TITLE
Accessing subfolder not working

### ISSUE THREAD

**Issue by afsheen1** [bramus/router#102]
Hello nice library..

recently I used it with app the index file is located in public folder with .htaccess file..

here is the code.

public/

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule . index.php [L]
```

and index.php

```
/**
 * Routing System
 * @package bramus/router
 */
$router = new \Bramus\Router\Router;

$router->get('/', function() { echo "INDEX!<br>"; });
$router->get('/about', function() { echo "About<br>"; });
$router->get('/contact', function() { echo "Contact<br>"; });

$router->run();

```

root folder .htaccess
```
RewriteEngine On
RewriteRule ^(.*)$ public/$1 [L]
```

after this index is working fine but when want access about/ or contact it still show index
anyone to help this.

note:
already I checked #82  and #13 

thanks

**Comment by leotop** [comment]
RewriteBase /subdir/

**Comment by bramus** [comment]
You only need a `.htaccess` in the `public` folder. If that doesn't work, try tweaking `RewriteBase` as suggested above.
