### ISSUE TITLE
Just a question please

### ISSUE THREAD

**Issue by kezenwa** [bramus/router#107]
Hello
have ben using this router for a little while but ran into an issue recently 

am looking on how to match following types of urls and also extracting their parameters if available .

1.   //example.com/any-thing-goes-pussy-cat-**guid**2378rysgd**prid**
how do i route the url to a controller only if part of the url contains a string that starts with **guid** and ends with **prid**

2.   //example.com/any-thing-goes-pussy-cat-**guid**2378hrhr73he8
how do i route the url to a controller only if part of the url contains a string that starts with **guid** followed alphanumeric characters.

3.   //example.com/any-thing-goes-pussy-cat-swer2378hrhr73he8**prix**
how do i route the url to a controller only if part of the url contains a string that ends with **prix**.

4.   //example.com/any-thing-goes-pussy-cat-2378738**qaz**
how do i route the url to a controller only if part of the url contains a string that is made of only numbers but end with **qaz** e.g  1234567**qaz**.

All the above of course would disregard query strings if they exists.

laravel router has a method that sort of works like **->contain()**, **->startWith()**, **->endWith()** and it's something similar that i seek or at least a way to implement such at the router level rather than resorting to making workarounds in the controller.

Thanks so much

**Comment by bramus** [comment]
There currently are no shorthands for `contains`/`startsWith`/`endsWith`.

What you can do instead is whip up a regular expression that matches it. startsWith and endsWith are easy, as there exist [PCRE meta characters](https://courses.cs.washington.edu/courses/cse190m/12sp/cheat-sheets/php-regex-cheat-sheet.pdf) for those.
