### ISSUE TITLE
No routes after a form submission using POST at localhost

### ISSUE THREAD

**Issue by LouisOuellet** [bramus/router#109]
Hi,
There seems to be an issue when the router is called with route at root (/) after a form submission using POST.
The router outputs 404, route not found!
I used your demo routes but here is my index file

```
<?php
session_start();

// Import Configurations
require_once 'config/app.php';


// Import Librairies
require_once 'src/lib/requirements.php';
require_once 'src/lib/database.php';
require_once 'src/lib/auth.php';
require_once 'src/lib/application.php';
require_once 'src/lib/router.php';

// Initialise Application
$app = new Application();
$router = new \Bramus\Router\Router();

// Import Routes
require_once 'config/routes.php';

if($app->validate()){

    // Initialise Librairies
    $conn = new Database($site['sql']['host'], $site['sql']['username'], $site['sql']['password'], $site['sql']['database']);
    $auth = new Auth();

    // Display Application
    if($auth->isLogin()){
        $router->run();
    } else {
        require_once 'src/templates/layout/signin.php';
    }
} else {
    require_once 'src/templates/layout/install.php';
}
```

The form itself is here src/templates/layout/signin.php and the routes are in config/routes.php. The routes are identical to the ones in your demo index.php file. I have simply stored them else where.

if I just click in the url and press enter after the 404, the proper route is displayed.

Server is running Apache2, PHP7 and MariaDB.

**Comment by bramus** [comment]
Did you properly hook the handling function to the correct methods? If your form uses `method="post"` then your route must respond to both `GET` and `POST` methods.

**Comment by LouisOuellet** [comment]
> Did you properly hook the handling function to the correct methods? If your form uses `method="post"` then your route must respond to both `GET` and `POST` methods.

Honestly I am new to php routing. As I mentionned I am testing with the included routes in your demo file. Here they are : 

config/routes.php
```
// Custom 404 Handler
$router->set404(function () {
    header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
    echo '404, route not found!<br />';
    echo $_SESSION['token'];
});
// Before Router Middleware
$router->before('GET', '/.*', function () {
    header('X-Powered-By: bramus/router');
});
// Static route: / (homepage)
$router->get('.*', function () {
    echo '<h1>bramus/router</h1><p>Try these routes:<p><ul><li>/hello/<em>name</em></li><li>/blog</li><li>/blog/<em>year</em></li><li>/blog/<em>year</em>/<em>month</em></li><li>/blog/<em>year</em>/<em>month</em>/<em>day</em></li><li>/movies</li><li>/movies/<em>id</em></li></ul>';
});
// Static route: / (homepage)
$router->get('/', function () {
    echo '<h1>bramus/router</h1><p>Try these routes:<p><ul><li>/hello/<em>name</em></li><li>/blog</li><li>/blog/<em>year</em></li><li>/blog/<em>year</em>/<em>month</em></li><li>/blog/<em>year</em>/<em>month</em>/<em>day</em></li><li>/movies</li><li>/movies/<em>id</em></li></ul>';
});
// Static route: /hello
$router->get('/hello', function () {
    echo '<h1>bramus/router</h1><p>Visit <code>/hello/<em>name</em></code> to get your Hello World mojo on!</p>';
});
// Dynamic route: /hello/name
$router->get('/hello/(\w+)', function ($name) {
    echo 'Hello ' . htmlentities($name);
});
// Dynamic route: /ohai/name/in/parts
$router->get('/ohai/(.*)', function ($url) {
    echo 'Ohai ' . htmlentities($url);
});
// Dynamic route with (successive) optional subpatterns: /blog(/year(/month(/day(/slug))))
$router->get('/blog(/\d{4}(/\d{2}(/\d{2}(/[a-z0-9_-]+)?)?)?)?', function ($year = null, $month = null, $day = null, $slug = null) {
    if (!$year) {
        echo 'Blog overview';

        return;
    }
    if (!$month) {
        echo 'Blog year overview (' . $year . ')';

        return;
    }
    if (!$day) {
        echo 'Blog month overview (' . $year . '-' . $month . ')';

        return;
    }
    if (!$slug) {
        echo 'Blog day overview (' . $year . '-' . $month . '-' . $day . ')';

        return;
    }
    echo 'Blogpost ' . htmlentities($slug) . ' detail (' . $year . '-' . $month . '-' . $day . ')';
});
// Subrouting
$router->mount('/movies', function () use ($router) {
    // will result in '/movies'
    $router->get('/', function () {
        echo 'movies overview';
    });
    // will result in '/movies'
    $router->post('/', function () {
        echo 'add movie';
    });
    // will result in '/movies/id'
    $router->get('/(\d+)', function ($id) {
        echo 'movie id ' . htmlentities($id);
    });
    // will result in '/movies/id'
    $router->put('/(\d+)', function ($id) {
        echo 'Update movie id ' . htmlentities($id);
    });
});
```

My index.php file skips the router if not logged on, application code integretty doesn't pass or config file is missing. Those are verified using $app->validate() and $auth->isLogin(). Don't think its related tho.

If you could expend your explanation about 

> properly hook the handling function to the correct methods

Thanks

**Comment by bramus** [comment]
If your form is sent using `POST`, then you also need to hook your handling function to that method. You can use [`$router->match()`](https://github.com/bramus/router#routing) or any of [the shorthands](https://github.com/bramus/router#routing-shorthands)

**Comment by LouisOuellet** [comment]
Actually I think I just figured it out. I should be calling the post method from your router class instead. But do I really need to duplicate the route to include both methods or can I write one route that would listen to both methods?

**Comment by LouisOuellet** [comment]
> If your form is sent using `POST`, then you also need to hook your handling function to that method. You can use [`$router->match()`](https://github.com/bramus/router#routing) or any of [the shorthands](https://github.com/bramus/router#routing-shorthands)

I see. Thanks!

**Comment by LouisOuellet** [comment]
Yup that worked!
Thanks again. Maybe next time I should take more time reading the README file xD
