### ISSUE TITLE
Im using the Class@Method and cant seem to figure out how to get varibles to the Views from the url

### ISSUE THREAD

**Issue by jdcw1998** [bramus/router#110]
hello if anyone knows how to get variables from view

$router->get('/hello/(\w+)', function($name) {
    echo 'Hello ' . htmlentities($name);
});
This above would work but if i tried putting below in a method and calling class@Method it would say cant find variable $name
   echo 'Hello ' . htmlentities($name);

if anyone knows how to fix this please let me know i dont know if i have to global the varibles some way and if so whats the best way to do that

**Comment by ghoshriju33** [comment]
I am also having the same problem.

**Comment by ghoshriju33** [comment]
> hello if anyone knows how to get variables from view
> 
> $router->get('/hello/(\w+)', function($name) {
> echo 'Hello ' . htmlentities($name);
> });
> This above would work but if i tried putting below in a method and calling class@Method it would say cant find variable $name
> echo 'Hello ' . htmlentities($name);
> 
> if anyone knows how to fix this please let me know i dont know if i have to global the varibles some way and if so whats the best way to do that

You need to explicitly define that you are going to use a global variable. When you define any variable like `$variable` it's scope is already global. In the class methods wherever you want to use it, just use the `global` keyword to let the method know that you are going to access the variable from a global scope. Like this `global $variable`. Then you can use it anywhere you want.

**Comment by DanFitMedia** [comment]
I'm also stuck with this problem. I've tried to follow the info form @ghoshriju33 but I still can't make sense of it.

Here's how I add the route:

`$router->all('/edit/{id}', 'Admin@edit');`

So with a URL like website.com/edit/123 it should route to the Admin class and call the edit method. This bit works perfectly.

But within the edit method I need to get access to the $id variable. In this case, 123. But this is where I'm stuck. I can't figure out how to get access to the $id variable.

I've read and re-read the docs, but nothing seems to answer.

I hope someone can clarify. Except for this issue, this router is brilliant. I hope I can figure this out too to complete a great router.

Many thanks

**Comment by bramus** [comment]
Just like you define a standalone function that takes an argument …

```php
$router->get('/hello/{name}', function($name) {
    echo 'Hello ' . htmlentities($name);
});
```

… you can define a function on your class that also takes an argument:

```php
class Handler {
    public static function detail($name) {
        echo 'Hello ' . htmlentities($name);
    }
}
$router->get('/hello/{name}', 'Handler@detail');
```

No need for globals at all.
