### ISSUE TITLE
Routes with trailing optional groups don't parse parameters properly in PHP 7.4+

### ISSUE THREAD

**Issue by csmith** [bramus/router#113]
In PHP 7.4.x the matches array returned by pcre_match_all changed slightly for trailing optional groups
(cf this PHP bug: https://bugs.php.net/bug.php?id=73948).

This code (which is how the router is [checking for matches](https://github.com/bramus/router/blob/master/src/Bramus/Router/Router.php#L345))

```php
preg_match_all('#^/(?:api/0.1/)?images/([0-9]+)(.json)?$#', '/api/0.1/images/1', $matches, PREG_OFFSET_CAPTURE);
print_r($matches[2]);
```

Gives the following in PHP 7.3.17:

```
Array
(
    [0] => 
)
```

But in PHP 7.4.0 onwards gives:

```
Array
(
    [0] => Array
        (
            [0] => 
            [1] => -1
        )
)
```

The fact that there's a `-1` element in the matches array breaks the [parameter mapping](https://github.com/bramus/router/blob/master/src/Bramus/Router/Router.php#L349-L358) and results in the router handlers receiving the wrong params.

**Comment by Altffenser** [comment]
I have solved this using _Iterator_
`iterator_to_array(new RecursiveIteratorIterator(new RecursiveArrayIterator($you_array])));`

**Comment by bramus** [comment]
This should be fixed with the merge of https://github.com/bramus/router/pull/114 — Can you verify?

**Comment by csmith** [comment]
Yep, that fix worked :+1:
