### ISSUE TITLE
CLI Routing

### ISSUE THREAD

**Issue by kaigoh** [bramus/router#116]
This isn't so much an issue, but more of a *"I hope this helps someone"*!

If you are using this library and need to be able to route via CLI requests, you can use the following code snippet to feed the router with the data it needs:

```
if(php_sapi_name() == "cli")
{
    $_SERVER['REQUEST_METHOD'] = "GET";
    $_SERVER['SERVER_PROTOCOL'] = "HTTP/1.1";
    // Make the CLI arguments look like a URL...
    $_SERVER['REQUEST_URI'] = "/".implode("/", array_slice($argv, 1));
}
```

Just put this at the top of your entry point script (i.e. index.php) and it will allow the route to use the command line arguments.

**Comment by bramus** [comment]
Thanks for the info. I'll close this issue, and will refer people to here in case they're also requesting something similar.
