### ISSUE TITLE
Public folder

### ISSUE THREAD

**Issue by Jcs1994** [bramus/router#117]
I'm using bramus router and it works fine but now I need to make public folder
![Capture d'écran Deepin_zone de sélection _20200614131135](https://user-images.githubusercontent.com/29231226/84591666-9a6a0200-ae40-11ea-8a54-ec8298b63b2c.png)

I need to route all files in src/Public/web without coding for every file 
```
$router->get("css/style.css", function(){
    echo file_get_contents(__DIR__ . "/src/Public/web/css/style.css");
});
```
because i have hundreds css file

is it possible with this library ?

**Comment by bredecl** [comment]
why don't do through htaccess?
```
RewriteEngine On
RewriteBase /
RewriteRule ^css/(.*)$ [path...]/src/Public/web/css/$1 [NC,L]
```
Or maybe with a wildcard:
```
$router->get("css/([A-Za-z0-9-_\.]+).css", function($filename){
    echo file_get_contents(__DIR__ . "/src/Public/web/css/".$filename.".css");
});
```
In this case be aware of header expiration rules.

**Comment by bramus** [comment]
As @bredecl hinted, you need to [set up URL rewriting](https://gist.github.com/bramus/5332525) so that the router only handles requests to files/folders that don't exist on disk.

This is also mentioned in the README.

**Comment by javadimoghadam** [comment]
Dear @bramus, Hope you doing fine 😊.
I used the @bredecl Method. but it's not working! 
I changed my (*.htaccess*) file. I use regex but it's not working.
this my code :
```php
$route->mount("/statics",function () use ($route) {
    $route->get("/css/([A-Za-z0-9-_\.]+).css", function($filename){
        echo file_get_contents(__DIR__ . "/views/statics/css/".$filename.".css");
    });
});
```
Can you help me?

**Comment by Homer1020** [comment]
I solved this problem just adding a last path that receives as a parameter the name of the file and looks for it in the public folder to return it, if it doesn't find it then it sends the famous 404.
```js
// ...previous routes
$router->get('/{publicFile}', function($publicFile) {
	$path = __DIR__ . "/../public/" . $publicFile;
	if(
		file_exists($path)
		&&
		!is_dir($path)
	)
  {
  	echo file_get_contents($path);
  } else {
    header('HTTP/1.1 404 Not Found');
  	$controller = new PagesController;
	$controller->error_404();
  }
});

$router->run();
```
I hope I have helped those who have this problem.
