### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by acicali** [bramus/router#123]
Just wondering. There are several pull requests (even very simple ones) to fix longstanding bugs, but they seem to have gone unnoticed.

This is a good router. I hope the work on it continues.

**Comment by bramus** [comment]
Yes it is, it's only low on my priority radar at this moment. Urgently need to make some time for it ;-)

**Comment by bramus** [comment]
I've merged some PRs that were still open (and could be merged). Feel free to test out master and I'll tag a new version if found OK.
