### ISSUE TITLE
Integration with template and Class@method

### ISSUE THREAD

**Issue by froid24** [bramus/router#129]
Hello,

You gave an example of integrating with a template class (with function() use ($tpl)), an example of how to use Dynamic Placeholder-based Route Patterns (like /ad/{id}), but how would you combine the two? I need to use that $tpl class (or any other class defined like in your example) in the method of the controller.

That means both the route parameters and that "use" variables must get to the controller method. How do I define the route in this case?

Thanks for helping.

Cheers!
Emil

**Comment by bramus** [comment]
`function($id) use ($tpl) { … }`

**Comment by froid24** [comment]
I mentioned in the title that I used the Class@method version; surely you can't expect that inline function to be used much, except for very simple tasks. So in what the examples states the syntax should be for using a controller method, how can the $tpl  variable reach that method?

$router->get('/ads/{id}', 'MyController@show'); // where does $tpl fit in this ?

I know that a workaround would be to declare $tpl as global, but it would be nice not to have to do that.

Thanks.

**Comment by bramus** [comment]
Apologies, I seem to have skipped over the title of your message and thereforewasn't aware you were talking about `Class@method`.

Now, to work around this limitation you could use a Singleton pattern to get a TemplateEngine instance in your controller method.

**Comment by ericel** [comment]
@bramus  can you expand on this? I am trying to use the router with Mustache template engine https://github.com/bobthecow/mustache.php.
I have mustache installed through composer.
I have a folder "views" in which I want my template files to be. What I want to do is load mustache as a default template engine and use it with the router.

The simple effort I tried so far leads to this error:
```
Warning: Undefined array key "REQUEST_METHOD" in /Applications/XAMPP/xamppfiles/htdocs/otcart/vendor/bramus/router/src/Bramus/Router/Router.php on line 225
PHP Warning:  Undefined array key "REQUEST_METHOD" in /Applications/XAMPP/xamppfiles/htdocs/otcart/vendor/bramus/router/src/Bramus/Router/Router.php on line 229
```
I am doing something wrong:
```
$mustache = new Mustache_Engine;
$router->get('/', function () {
            echo $mustache->render('home.html');
         });
```
What will be the setup here? Forgive my ignorance. Just getting back to PHP.
