### ISSUE TITLE
Routes using a Class@Method do not work using autoloaders, instead of pre-defined classes.

### ISSUE THREAD

**Issue by leandrotijink** [bramus/router#130]
Hi there,

Yesterday I ran into an issue that occurs when you are dependent on autoloaders to load the necessary classes. For example, when the class you want the router to go to doesn't yet exist, the is_callable() function inside invoke() will fail, and won't trigger a 404 page either.

Because it checks whether the Class@Method is callable, instead of trying to instantiate it first, the autoloader doesn't get triggered.

This issue can be reproduced using version 1.5 of the library (the latest one as of writing this), using PHP 7.4.x, and by following these steps:

Create a file named NonLoadedClass.php:
```PHP
class NonLoadedClass
{
   
   function Method()
   {
      echo 'This will not show up, even though it should.';
   }
}
```
Then, create a file named index.php:
```php
// Define an autoloader.
spl_autoload_register(function($className) {
   $file = ROOT.$className.'.php';
   $file = str_replace('\\', DIRECTORY_SEPARATOR, $file);
   if (file_exists($file)) {
      require $file;
   }
});

// Instantiate the router
$router = new Router();

// Define a route with a Class@Method that has not been defined yet
$router->get('/test-url', '\NonLoadedClass@Method');

// Run it
$router->run();
```
You may notice the screen will stay blank when you load the page, instead of showing the expected echo.

The issue lies in the following code:
```php
// Make sure it's callable
if (is_callable(array($controller, $method))) {
   if ((new \ReflectionMethod($controller, $method))->isStatic()) {
      forward_static_call_array(array($controller, $method), $params);
   } else {

      // Make sure we have an instance, to prevent "non-static method … should not be called statically" warnings
      if (\is_string($controller)) {
         $controller = new $controller();
      }
      call_user_func_array(array($controller, $method), $params);
   }
}
```

I'd suggest the following changes to be implemented to account for those that use autoloaders extensively, and can't define/load the necessary classes beforehand. 
```php
if (\is_string($controller)) {
   try {
      // Trigger the autoloader
      $controller = new $controller();

      // Make sure it's callable
      if (is_callable(array($controller, $method))) {
         if ((new \ReflectionMethod($controller, $method))->isStatic()) {
            forward_static_call_array(array($controller, $method), $params);
         } else {
            call_user_func_array(array($controller, $method), $params);
         }
      }
   } catch (\Throwable $e) {
      // Fall back to 404
      $this->trigger404();
   }
}
```

**Comment by bramus** [comment]
Pretty weird that the autoloader isn't triggered. Wasn't aware of this.

Now, problem with creating a new instance as you suggest is that that piece of code won't always work: some constructors might require a few arguments while others — such as the one in your example — don't.

**Comment by germangamboa95** [comment]
The offending code is this 
https://github.com/bramus/router/blob/6adc0182dc6b0ebc22fd10543f65a36de10d8c05/src/Bramus/Router/Router.php#L402

It seems that `is_callable` does not play nice with namespaces. What we can do is is remove that check and let the code try to build the class and call the method.

**Comment by Edydeyemi** [comment]
I experienced this today using composer's autoloader. My workaround was to include the Controller class in the route file before defining the routes. I believe this is just a minor inconvenience; Bramus offers way much functionality for me 😀

**Comment by leandrotijink** [comment]
@Edydeyemi I ended up using the code I suggested at first, as it works well for my use case. But a require_once does the job as well indeed.

**Comment by mjoris** [comment]
@Edydeyemi actually i never experienced any problem with `bramus/router` and composer's autoloader in PHP7. 

Actually I use an autoload classmap in `composer.json`:
`    "autoload": {
        "classmap": ["src/"]
    }`
Of course, upon new classes in `src`, or namespace changes, you need to `composer dump-autoload`. Next, after requiring composer's autoloader, `bramus/router` can find any of my controller classes.

**Comment by Edydeyemi** [comment]
Wow @mjoris thanks for the heads-up. I tried it and it worked! 😲😲. Jolly good stuff.

**Comment by mjoris** [comment]
@Edydeyemi  you're welcome  🙂

**Comment by bramus** [comment]
Thanks for chiming in here, @mjoris!
