### ISSUE TITLE
Using -'s breaks the router

### ISSUE THREAD

**Issue by RiversideRocks** [bramus/router#131]
I use your router on my site and its quite useful. My only complaint is that it break upon requesting a custom path with -.

For example, on my site I have a route for /users/(\w+). Requesting /users/RiversideRocks works fine, but requesting /users/code-alt fails.

I've checked and this isn't an issue with the DB.

**Comment by bramus** [comment]
Please refer to [the provided documentation](https://github.com/bramus/router#dynamic-pcre-based-route-patterns), as `(\w+)` PCRE pattern does not capture the `-` character.
