### ISSUE TITLE
Multiple Custom 404 Page

### ISSUE THREAD

**Issue by uvulpos** [bramus/router#144]
Hey there,
I want to build a website with a tiny build in API.

`/dashboard` → Homepage
`/api/getUser` → API

My Problem now is: I have an HTML 404 defined, but I want to define a custom JSON 404 for my API mount. But this is not working:
```php
$router->mount('/api', function() use ($router) {
  $router->get('/', 'APIHandler@index');
  $router->set404(function() {
    echo "api nono";
  });
});
```

So, this is a Feature Request to make 404 in mounts overwritable 😄

**Comment by bramus** [comment]
This is currently not supported yet I'd happily accept a PR that provides this.

**Comment by uvulpos** [comment]
Hey @bramus,

would be great, if you could review my PRs 😄 
This is just a little poke that my PRs are ready to merge

**Comment by bramus** [comment]
@uvulpos Thanks for the reminder … merged!
