### ISSUE TITLE
set404 not working

### ISSUE THREAD

**Issue by Venloress** [bramus/router#154]
Not working
```
$router->set404('/api(/.*)?', function() {
    header('HTTP/1.1 404 Not Found');
    header('Content-Type: application/json');

    $jsonArray = array();
    $jsonArray['status'] = "404";
    $jsonArray['status_text'] = "route not defined";

    echo json_encode($jsonArray);
});
```

**Comment by uvulpos** [comment]
@bramus you need to make a new release, my pr got just merged but not in prod so the README is ahead ;)

**Comment by uvulpos** [comment]
(Reminder) Please publish a new release!
@bramus

**Comment by bramus** [comment]
Thanks for the reminder, @uvulpos. Version 1.6 has just been tagged and pushed. Might take a minute before Packagist picks it up.
