### ISSUE TITLE
Warning: Undefined array key "GET" in Router.php on line 292

### ISSUE THREAD

**Issue by mdmomeni** [bramus/router#167]
```PHP
$router = new \Bramus\Router\Router();
$router->run();
$router->get("/hi", function () {
    echo "hi";
});
```
I get this for the `/hi` route
```
Warning: Undefined array key "GET" in C:\xampp\htdocs\Expreience share\vendor\bramus\router\src\Bramus\Router\Router.php on line 292
```

**Comment by uvulpos** [comment]
Hi @mdmomeni,
this is correct indeed. You first add your route to the routes array via
```php
$router->get("/hi", function () {
    echo "hi";
});
```
and **THEN** you run the `run` method to execute your defined function if it's got called 🙂

So let's fix your code:
```php
$router = new \Bramus\Router\Router();
$router->get("/hi", function () {
    echo "hi";
});
$router->run();
```
I hope this was helpful, and you're now able to build your application 😉

~ Tim

**Comment by mdmomeni** [comment]
Thank you I didn't read the docs carefully.
