### ISSUE TITLE
404 not working properly in version 1.6

### ISSUE THREAD

**Issue by mjoris** [bramus/router#170]
Since @uvulpos 's commit on multiple 404 routes,
- bramus/router does NOT generate a 404 status code when there is no custom 404 handler
- bramus/router emits a warning (PHP 8) when there is no root ('/') custom 404 handler

when none of the routes match

#169 i guess this commit fixes this malfunction with any combination of 404 routes

**Comment by bramus** [comment]
Should be fixed via #170
