### ISSUE TITLE
Drop support for old PHP versions

### ISSUE THREAD

**Issue by neondotta** [bramus/router#171]
Found two problems on PHP 5.3.

**line 28 and 341** has problems to create array ( change [] to array() )

**line 395** use boolval, but not work in PHP 5.3

**Comment by bramus** [comment]
Instead of trying to fix these, support for older PHP versions should be dropped. I am open to a PR that adjusts this. I’ll leave this issue open.

**Comment by bramus** [comment]
Closing this one in favour of #147
