### ISSUE TITLE
Warning: Undefined array key "GET" in C:\xampp\htdocs\vendor\bramus\router\src\Bramus\Router\Router.php on line 292

### ISSUE THREAD

**Issue by OskiBoski483** [bramus/router#175]
Warning: Undefined array key "GET" in C:\xampp\htdocs\vendor\bramus\router\src\Bramus\Router\Router.php on line 292

**Comment by uvulpos** [comment]
Could you please give me some more context to solve this problem? 
Can you show me your implementation of your 404 handler?
How did you execute your request?
Have you checked the [documentation](https://github.com/bramus/router#custom-404﻿﻿)?
Which version of php and of the router do you use?
