### ISSUE TITLE
Method connect missing

### ISSUE THREAD

**Issue by Jcs1994** [bramus/router#181]
Hi,

On my logs, sometimes i get this error, i tihnk its dues to a proxy

`Type: ErrorException; Message: Undefined index: CONNECT; File: /var/www/html/vendor/bramus/router/src/Bramus/Router/Router.php; Line: 292;`

**Comment by bramus** [comment]
It’s a bug that is also described in https://github.com/bramus/router/issues/182. Closing this one in favor of #182.
