### ISSUE TITLE
404 handling breaks when no routes for a particular method are defined

### ISSUE THREAD

**Issue by matthew-e-brown** [bramus/router#182]
If I have the following set of routes:

```php
$router = new \Bramus\Router\Router();

$router->get('/', function() { /* ... */ });

$router->mount('/page-a', function() use (&$router) {
    $router->get('/sub-a', function() { /* ... */ });
    $router->get('/sub-b', function() { /* ... */ });
});

$router->mount('/page-b', function() use (&$router) {
    $router->get('/sub-a', function() { /* ... */ });
    $router->get('/sub-b', function() { /* ... */ });
});

$router->run();
```

then navigating to `/nonexistent-page` in a browser will correctly display the browser's standard 404 page. 

However, if I attempt to send a *POST* request to `/nonexistent-page`, then I get a `200 OK` and see the following error instead:

> **Warning**: Undefined array key "POST" in **C:\Users\Matthew\\...\backend\vendor\bramus\router\src\Bramus\Router\Router.php** on line **292**
> 
> **Warning**: Cannot modify header information - headers already sent by (output started at C:\Users\Matthew\\...\backend\vendor\bramus\router\src\Bramus\Router\Router.php:292) in **C:\Users\Matthew\\...\backend\vendor\bramus\router\src\Bramus\Router\Router.php** on line **374**

However&sup2;, if I set any POST route on the router, i.e.

```php
$router = new \Bramus\Router\Router();

// -- snip

$router->post('/', function() {
    echo 'yeet';
});

$router->run();
```

then all other POST endpoints now correctly respond with 404.

This behavior is also true for `PUT`, `DELETE`, `OPTIONS`, and `PATCH`. Since `HEAD` is handled by a special case, it works just fine and returns 404 -- see [curl-logs.txt](https://github.com/bramus/router/files/8799502/curl-logs.txt).

I doubt that this behaviour is intended. In my eyes, any undefined route/match should get 404'd, i.e.

```php
// This should give me a 404 for every route, but instead it spits out errors.
$router = new \Bramus\Router\Router();
$router->run();
```

If it is intended, and the developer is simply expected to define handlers for all method types, then I guess that's my answer.

---

Per the error message, this issue comes from line 292 (`Router::run()`):

https://github.com/bramus/router/blob/55657b76da8a0a509250fb55b9dd24e1aa237eba/src/Bramus/Router/Router.php#L290-L298

when the router attempts to index into `$this->afterRoutes` using the current method. Since `afterRoutes` starts as `array()`, there are no keys for **any** method to start, which makes this an index out of range call.

Funny to note that, further down at line 371 (`Router::trigger404()`), there is actually an `isset` check before attempting to invoke the `notFoundCallback` for `'/'`:

https://github.com/bramus/router/blob/55657b76da8a0a509250fb55b9dd24e1aa237eba/src/Bramus/Router/Router.php#L371-L375

With that in mind, there are two ways that I've found to fix this: 

1.  Adding a check to line 292 before invoking:

    ```php
    $match = $this->afterRoutes[$this->requestedMethod] ?? '/';
    $this->trigger404($match);
    // Probably `if (isset())` instead of `??` for backwards compat.
    ```

2.  Giving the routes' method keys default values:

    ```php
    /**
     * @var array The route patterns and their handling functions
     */
    private $afterRoutes = array(
      'GET' => array(),
      'POST' => array(),
      'PUT' => array(),
      'DELETE' => array(),
      'OPTIONS' => array(),
      'PATCH' => array(),
      'HEAD' => array()
    );

    /**
     * @var array The before middleware route patterns and their handling functions
     */
    private $beforeRoutes = array(
      'GET' => array(),
      'POST' => array(),
      'PUT' => array(),
      'DELETE' => array(),
      'OPTIONS' => array(),
      'PATCH' => array(),
      'HEAD' => array()
    );
    ```

I would love to submit a pull request with either of these changes for further review, since I've already got it started. It should probably receive a bit more thorough testing.

Cheers,
-- Matt

**Comment by bramus** [comment]
A simple check for the existence of `$this->afterRoutes[$this->requestedMethod]` should suffice. I am open to a PR that fixes this.
