### ISSUE TITLE
$route->set404 = redirect to ?uri= if folder exist

### ISSUE THREAD

**Issue by hroma** [bramus/router#193]
Hi, 
I want to return a 404 error page for all request starting with WEB_INF like http: //domain.com/**WEB-INF**
Is it normal behavior that url is redirected to http: //domain.com/**WEB-INF?uri=WEB-INF**. 
Please note that **WEB-INF** folder really exist on my serverRoot and below rule works fine if folder doesn't exist...

```
$router->set404('/WEB_INF(/.*)?', function () {
    require '/404.php';
});
```
Thanks

**Comment by uvulpos** [comment]
The 404 Method is just a fallback, when no file or router endpoint got found. You cannot use it to hide a folder. You have two options you can do:
1. You could have a public folder, where an index.html is, that requires the router.php, which is as all the other files as well, not publicly available. Then the `WEB-INF` folder would probably also not accessible via the web and you dont have to do anything, there will be a 404 by default
2. You dig deeper into your Apache or Nginx server configuration and search for a way to just make it not routable anymore. But then this would have nothing to do anymore with the router.

Hope that helps (even half a year / almost one year later) 🙂

**Comment by uvulpos** [comment]
Closed due to no response. If you need further support, please open a new issue :)
