### ISSUE TITLE
POST variable

### ISSUE THREAD

**Issue by marekkobida** [bramus/router#20]
How I can call POST variable domain in `$router->post` callback?

    $router->post("/login", function () {

    });

    <form action="login" method="post">
        <input type="text" name="domain">
        <input type="submit" value="Odoslať formulár">
    </form>

**Comment by wilhelmpaulm** [comment]
@marekkobida  $_POST["domain"] like you would normally do.

**Comment by aa21** [comment]
I have this same issue and there is no documentation anywhere. 

I'd have thought `$router->post("/login", function ($params) {` would mean `$params` would allow the form POST parameters to be available to the callback but it doesn't seem to be the case. `$_POST` is empty also.

> How I can call POST variable domain in `$router->post` callback?
> 
> ```
> $router->post("/login", function () {
> 
> });
> 
> <form action="login" method="post">
>     <input type="text" name="domain">
>     <input type="submit" value="Odoslať formulár">
> </form>
> ```

**Comment by aa21** [comment]
> $_POST parameter work for me

Yes I can get `$_POST` now - the error was clientside. I was posting JSON instead of proper POST data.

However it's still bothering me that inside the POST callback you have to call a global array instead of function argument ... but I suppose that's the PHP way anyway.
