### ISSUE TITLE
Method to call hooked routes (subrequest)

### ISSUE THREAD

**Issue by RinkAttendant6** [bramus/router#28]
It would be extremely useful to be able to call a hooked route given an HTTP method and path.

For example:

``` php
$router->get('/hello/(\w+)', function ($name) {
    echo "Hello $name";
});

$router->call('GET', '/hello/Tyler'); // should echo "Hello Tyler"
```

The `call` method should work without having to do `$router->run()` first.
This would provide similar functionality to the `subRequest()` method in Slim 3 and Silex.

IMO it is an appropriate responsibility of the router to provide such a functionality as the router handles the pattern matching and callbacks.
Alternatively you can provide a getter method to return the contents of `$afterRoutes` to make it possible to implement such functionality in applications using this library.

**Comment by sant0ro** [comment]
A nice idea. But that kills the concept of a Router.

In fact, we can add that, with the approval of @bramus, but is necessary that the call method be linked with a node.

A nice idea and i will be happy to code that, if Bramus accept.

**Comment by RinkAttendant6** [comment]
@sant0ro Thank you for your consideration.
My current use case is to invoke a private, local API that uses this library to handle the routing. The only way I can think of to access the API is to (1) move all the API callbacks to class methods, instantiate the required class as necessary, and call the method both from the API and the application or (2) make a local HTTP request to the API.

Option 1 increases the coupling of the application to the API and option 2 seems like a lot of overhead to use the network for something running locally.

**Comment by sant0ro** [comment]
You don't need instantiate each Callback. Create a Singleton Pattern with a Factory Pattern.

Doing a union of those, you will get exactly what you need. A Response Handler that "redirects" to a specific Handler and "invoke" it using Singleton Lazy access. (Static Binding of getInstance()). You only need have a base Interface and a Singleton Model. Your handlers can extends this Model.

Good luck.

**Comment by lai0n** [comment]
A good idea. While there is not this method, I think you can code something like this:
 
```
$router->get('/hello/(\w+)', function ($name) {
    echo "Hello $name";
});

$_SERVER['REQUEST_URI'] = 'hello/Tyler'; 
$router->run(); 
```

**Comment by bramus** [comment]
Whilst I like the idea of making sub requests, it would – if you want to cover all bases _([which Silex/Symfony does](http://silex.sensiolabs.org/doc/cookbook/sub_requests.html))_ – necessitate a `Request` class (and quite possibly a `Response` class too), as you'd want to override the contents of `$_GET`, `$_POST`, `$_SESSION`, and `$_COOKIE` for the sub request _(and then revert back to the original values after said sub request has been made)_.

Not covering all bases doesn't seem a viable/proper option to me.

Take this example (as provided at the top of this thread):
````
$router->get('/hello/(\w+)', function ($name) {
    echo "Hello $name";
});

$router->call('GET', '/hello/Tyler'); // should echo "Hello Tyler"
````
It indeed will work as it only relies on dynamic route patterns.

But this example below won't work properly, as it relies not only on dynamic route patterns but also on `$_POST`, etc.
````
$router->post('/subscribe', function () {
    MailingList::subscribe(Request::postValue('email'));
});

$router->get('/some/url', function () {
    $router->call('POST', '/subscribe'); // pass call to `/subscribe` route
});
````

My preference would be to cover all bases, yet then it will exceed the scope of the router itself.

~

Circling back to your original problem the by you suggested solution 2 (viz. making a local request) looks a viable one to me:
- If you make requests to the local machine (viz. 127.0.0.1, or a name that resolves to that) you won't have that much (network traffic) overhead I guess _(testing needed though)_.
- Making a new request will enforce correct data to be found in `$_GET` and `$_POST` (and `$_COOKIE` + `$_SESSION` if you use a cookie jar and pass the session id with the new request).

Regards,
Bramus.
