### ISSUE TITLE
subfolder issue

### ISSUE THREAD

**Issue by ghost** [bramus/router#30]
I'm having a problem using bramus\router in subfolder, like that #13. The issue comes from `getBasePath` method, if I remove the one, the issue is fixed.

**Comment by lai0n** [comment]
I fixed the issue like this
https://github.com/lai0n/router/commit/18ba190988f1477df9b9587d4836be46d8ade814

**Comment by bramus** [comment]
Hi @lai0n, could you make a PR for this one?

**Comment by lai0n** [comment]
#31

**Comment by bramus** [comment]
Closing this one, as the PR created by the author (https://github.com/bramus/router/pull/31) was closed by the original author himself.
