### ISSUE TITLE
Inheritance. 

### ISSUE THREAD

**Issue by dylanharty** [bramus/router#32]
Please make the handle classes and other classes override-able but using protected methods instead of private. 

example:
`private function handle(...){
}`

Cannot be overridden from a child. Make it 
`protected function handle(...){
}`

**Comment by bramus** [comment]
Won't implement this, as it goes against the open/closed principle. Being able to change the `handle` method can do more wrong than good.

Sidenote: what exactly do you want to do? Perhaps it's a missing feature that can be PR'd into this project?
