### ISSUE TITLE
Router always redirect to /

### ISSUE THREAD

**Issue by SundownDEV** [bramus/router#36]
Hi I installed the router on my vps for my framework Daimyo https://github.com/SundownDEV/Daimyo
But after installing with composer, the router doesn't work, when calling "/" route it work properly but calling "/test" or whatever even wrong routes doesn't work it always redirect to "/" route.

My .htaccess
~~~php
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
~~~

My index.php
~~~php
<?php
	ini_set('display_errors', 1);
	ini_set('display_startup_errors', 1);
	error_reporting(E_ALL);
	
	require __DIR__.'/../app/system.php';

	require_once __DIR__.'/../vendor/autoload.php';

	$app = new \App\Application($debug = true);

	require __DIR__.'/../app/routes.php';

	$app->run();
~~~

Route.php
~~~php
<?php

/*$app->before('GET', '/.*', function() use ($app) {
    # This will be always executed
});*/

$app->get('/', function () use ($app) {
	echo "<b>Coming soon</b><br>";
	echo 'Devbreak by @SundownDEV';
});

$app->get('/aze', function () use ($app) {
	echo "test";
});


$app->mount('/test', function () use ($app) {
	$app->router('test'); // include test routes
});

$app->set404(function () use ($app) {
	# Example :
    # $app->render(['src' => '404', 'views' => '404'], ['title' => 'Page not found']);

    echo "404 error";
});
~~~

Help please :(

**Comment by SundownDEV** [comment]
Fixed. It just was ISPConfig.

**Comment by josefelipetto** [comment]
Please, could you say what you did to fix this? I'm having the same problem and i'm using Apache. 
I'm just defining the routes on the index.php and then $router->run(), but it just executes '/' route. 
Could you help me please? Thanks!

**Comment by SundownDEV** [comment]
Hi, could you paste your index.php and .htaccess please ?

**Comment by josefelipetto** [comment]
Hi, thank you for the response! 

Here's my index.php 

```PHP

<?php

define('__DATA_FOLDER', 'src/resources');

require 'vendor/autoload.php';

$router = new \Bramus\Router\Router();

$router->set404(function () {
    header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
    echo 'Ish, rota errada. Verifique certinho aí :) ';
});


// Autenticar
$router->get('/','\App\Controllers\LoginController@index');
$router->get('/login','\App\Controllers\LoginController@index');

$router->post('/login','\App\Controllers\LoginController@login');


// Cadastrar
$router->get('/user', '\App\Controllers\UserController@index');
$router->post('/user', '\App\Controllers\UserController@newUser');

$router->get('/main','\App\Controllers\MainController@index');


$router->run();

```
And here is my .htaccess
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]

```

Thank you!

**Comment by SundownDEV** [comment]
could you clarify what's the issue here ? the "/" route doesn't work or it's the only route that work ?

**Comment by josefelipetto** [comment]
It's the only route that works.

**Comment by SundownDEV** [comment]
are you sure the [url rewriting](https://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2) in apache is enabled ?

**Comment by josefelipetto** [comment]
Yes, i'm sure. I've just followed the instructions of the url rewriting link that you sent just to make sure, but it still doesn't work. When i run with the built-in php server using the code snippet to simulate the .htaccess, it works, so i guess it's something about the url rewriting rule in Apache. Thanks for clarify this to me! I'll keep digging into it to find a solution.

**Comment by bramus** [comment]
Don't forget to restart Apache after enabling the rewrite extensions.

**Comment by jurakin** [comment]
I had to set the `basePath`, because I forgot I was in some directory.

So, add this line and add the path before the links as well.
```
$router->setBasePath("/path/to/your/parent/folder/");
```
