### ISSUE TITLE
How to make a default router?

### ISSUE THREAD

**Issue by sn01615** [bramus/router#40]

**Comment by sn01615** [comment]
Like this? 
```php
$router->match('GET|POST|PUT|DELETE|OPTIONS|PATCH|HEAD', '.*', function () {
    
});
```

**Comment by bramus** [comment]
Looking at the provided documentation, mainly the [Routing](https://github.com/bramus/router#routing) and [Route Patterns](https://github.com/bramus/router#route-patterns), that indeed looks like something that would work. Just give it a test yourself ;)
