### ISSUE TITLE
Match function doesn't work (404 error)

### ISSUE THREAD

**Issue by SundownDEV** [bramus/router#42]
Hi, 

created a route for my contact page
~~~php
$app->match('GET|POST','/contact', function () use ($app) {
	$app->render(['src' => 'contact', 'views' => 'contact']);
});
~~~

and I get 404 error when trying GET **or** POST method on `localhost/contact`.

Other functions work fine

Im using this atm:
~~~php
$app->mount('/contact', function () use ($app) {
	$app->get('/', function () use ($app) {
		$app->render(['src' => 'contact','views' => 'contact'], ['title' => 'Me contacter']);
	});

	$app->post('/validate', function () use ($app) {
		$app->render(['src' => 'contact','views' => 'contact'], ['title' => 'Me contacter']);
	});
});
~~~

Thanks for help

**Comment by bramus** [comment]
Could you clarify which code snippet you are using. It's not clear to me if you are using the first, the second, or both.

**Comment by SundownDEV** [comment]
I don't understand your question

~~~php
$app->match('GET|POST','/contact', function () use ($app) {
	$app->render(['src' => 'contact', 'views' => 'contact']);
});
~~~

is the route that doesn't work

**Comment by SundownDEV** [comment]
the first one is the one that doesn't work, the post about the match function which doesn't work. The second one is the route which works and Im using actually. Im not using both at the same time.

**Comment by SundownDEV** [comment]
up, still not fixed

**Comment by bramus** [comment]
Closing this one as:

- The unit tests show no errors
- A minimal testcase works just fine:

```php
<?php

require './../vendor/autoload.php';

$router = new \Bramus\Router\Router();

$router->match('GET|POST','/contact', function() {
	echo 'GET or POST to /contact' . PHP_EOL;
});

$router->run();
```

To test this piece of code, one can use PHP's built-in webserver (e.g. `php -S localhost:8080 -t www`) in combination with `curl`:

```
bramus in ~/repos/router-test
$ curl -X OPTIONS http://localhost:8080/contact
bramus in ~/repos/router-test
$ curl -X POST http://localhost:8080/contact
GET or POST to /contact
bramus in ~/repos/router-test
$ curl -X GET http://localhost:8080/contact
GET or POST to /contact
bramus in ~/repos/router-test
$ curl -X PUT http://localhost:8080/contact
bramus in ~/repos/router-test
$ curl -X PATCH http://localhost:8080/contact
bramus in ~/repos/router-test
$ 
```

Regards,
Bramus.

**Comment by bramus** [comment]
In case somebody in the near future reading this thread wants to know what the culprit was: https://github.com/SundownDEV/Daimyo/commit/3fb5b75e0635341cca091dedc245bf9440ad21c3

**Comment by SundownDEV** [comment]
haha yes I didn't expected that, I saw and fixed it after your answer, my bad sorry ^^'
