### ISSUE TITLE
http/https in routes?

### ISSUE THREAD

**Issue by aolko** [bramus/router#48]
is it possible to have following route format `/browse/1511857497/http://google.com/` or `/browse/http://google.com/1511857497` (in this case timestamp is a separate entity)?

**Comment by bramus** [comment]
Yes that's possible, as long as you write a matching regex that will catch it. This is documented in [the route patterns part](https://github.com/bramus/router#route-patterns) of the included documentation.

**Comment by aolko** [comment]
sadly my regex won't work at all
`((?:http|https):\/\/)((?:[\w-]+)(?:\.[\w-]+)+)(?:[\w.,@?^=%&amp;:\/~+#-]*[\w@?^=%&amp;\/~+#-])`

**Comment by bramus** [comment]
I think you can simplify the last part of your expression by falling back to `(.*)` to extract the URL. Something like this: `/browse/(\d+)/(.*)`

See https://regex101.com/r/a2SxAC/1/ for a working example.

**Comment by aolko** [comment]
yes, it works, but what if my timestamp is not required? `?()` construction breaks the route if the first argument is not required

**Comment by bramus** [comment]
You should use the `?` modifier as a suffix, not a prefix. See [the documentation on optional route subpatterns](https://github.com/bramus/router#optional-route-subpatterns) for more info.
