### ISSUE TITLE
Conditional Route Pattern

### ISSUE THREAD

**Issue by parkerj** [bramus/router#49]
This is a feature request, but not sure if it is possible or beneficial. Would it be possible to add a conditional route pattern?
```
// Require composer autoloader
require __DIR__ . '/vendor/autoload.php';
// Create Router instance
$router = new \Bramus\Router\Router();
// Conditional GET
$router->get([ '/users/', '/users/(\w+)/' ], function() { /* ... */ });
```
In the GET example above, it is conditional based on number of records and page offset to determine if there is pagination. If its the first page, then return `/users/`. If we navigate to the second page, then the pattern would match `/users/2/`. Again, I don't know if this is possible, but would love to see this feature.

**Comment by bramus** [comment]
You can use [conditional route patterns](https://github.com/bramus/router#optional-route-subpatterns) for this.
