### ISSUE TITLE
Controller that handles error 404

### ISSUE THREAD

**Issue by ArtyumX** [bramus/router#52]
Hey,

was wondering if it was possible to let a controller@method() handles error 404 like :
```php
$router->set404('ErrorController@notFound');
```
[rather than writing a function](https://github.com/bramus/router#custom-404) directly in my **routes.php** file.

**Comment by sant0ro** [comment]
That would be interesting. I'll do a research about it 😄

**Comment by ArtyumX** [comment]
Thanks a lot!
Looking forward to get this feature implemented to the router.

**Comment by bramus** [comment]
Fixed in 6cdbcf30f2ce9166a4faba34c8f1c8f20c083325. I've release version 1.3 with this change contained.
