### ISSUE TITLE
Domain/subdomain routing feature

### ISSUE THREAD

**Issue by ArtyumX** [bramus/router#56]
Hi,

is there any chance for this feature to be implemented in a near future ?

Simple example : 
```php
$router->mount(['domain' => 'website.com'], function() use ($router) {
    $router->get('/', 'HomepageController@index');
});

$router->mount(['domain' => 'api.website.com'], function() use ($router) {
    $router->get('/', 'ApiController@index');
});
```

This would be so useful and less redundant for my projects to have one single project folder for the website and the api rather than having 2 seperates project folder for each sub domains/domains.

Thanks.

**Comment by bramus** [comment]
This looks like a very specific use case which is not that common. There are currently no plans to implement domain matching in `bramus/router` itself.

What you could do is something like this:
````php

$router = new \Bramus\Router\Router();

if (in_array($_SERVER['SERVER_NAME'], ['website.com', 'www.website.com']) {
    // mount HomepageController routes
}


if (in_array($_SERVER['SERVER_NAME'], ['api.website.com']) {
    // mount ApiController routes
}

$router->run();
````

Hope this solves your issue.

**Comment by ArtyumX** [comment]
I understand, thanks.
Good workaround, I planned to do something very similar.
