### ISSUE TITLE
how to allow patterns with dot to work

### ISSUE THREAD

**Issue by drnkwati** [bramus/router#66]
Hi
I cant get patterns with dots to work. For example
/files/main_logo.jpg
does not work due to the dot. I have tried `([A-Za-z0-9-_/.]+), ([^/])` and a few others 
but they don't work

**Comment by eminks** [comment]
the code work for me
```
$router->get('/get/ui(.*)/(.*)', function ($id,$kad) {
  echo "deneme-get ".$id;
  echo "<br>";
  echo "deneme-fd ".$kad;
});

```

**Comment by ovflowd** [comment]
You also can just use something like that: (That's also available in Laravel)

```php
$router->get('/get/{one}/{two}', function ($one, $two) {
  echo $one;
  echo "<br>";
  echo $two;
});
```

**Comment by drnkwati** [comment]
Seriously! Will fast route like patterns work.
/{one}/{two}
But how do I allow a dot to be included.

**Comment by ovflowd** [comment]
I think dot actually it's allowed on the fast patterns implementation.

Just try out :) I haven't actually tried it with dots.

**Comment by bramus** [comment]
Normally things should work by “just” adding the period to the a base regex such as `[A-z0-9]+`. The result would then be `[A-z0-9\.]+`: _(Note: the `.` is escaped with a `\`)_

However, when testing this using the built-in PHP webserver, it yields no match — even though tools like https://regex101.com/r/aXGA7Z/1/ do validate the regex itself …

**Comment by drnkwati** [comment]
i was not escaping the dot. This works fine
`[A-z0-9\.]+`
