### ISSUE TITLE
$_POST problem

### ISSUE THREAD

**Issue by abmmhasan** [bramus/router#67]
$_POST is not working. I can't retrieve post variable with that or not even $_REQUEST.
`$router->post('/', function () { ; });`
Let me know, how to detect post variables?
Like if I wanna get the value of $_POST['Key'] or wanna see all the key, value of $_POST; what to do?

**Comment by parkerj** [comment]
Try this:

```
$router->post('/', function () {
    error_log(var_export($_POST, true));
});
```

The above code will post $_POST variables to your system's error log, so you can see if it is working or not.

**Comment by bramus** [comment]
Please make sure that you're meeting [the necessary prerequisites](https://github.com/bramus/router#prerequisitesrequirements). Since you can't see anything in `$_REQUEST` (and thus `$_POST`), I suspect you haven't set up URL Rewriting properly.

Also make sure you're starting your router with `$router->run();`, otherwise nothing will happen.

**Comment by abmmhasan** [comment]
```
$router = new Router;
    $router->set404(function () {
        header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
        echo '404, route not found!';
    });

    // Before Router Middleware
    $router->before('GET', '/.*', function () {
		header('Content-type: application/json');
    });
    // Subrouting
    $router->mount('/mff', function () use ($router) {
        $router->get('/', function () {
			echo "Get Request";
        });
        $router->post('/', function () {
            $messages = array();if(isset($_request))$chk='POST Set';else $chk='POST not Set';
			array_push($messages,
			array(
			'speech'=>'TEST FLY'.$chk,
			'type'=>0
			));
            echo json_encode(array("messages"=>$messages), JSON_UNESCAPED_UNICODE);
        });
    });

$router->run();
```
Is what I'm using! Please let me know whats the problem there!

**Comment by ovflowd** [comment]
Why are you doing this:

```php
$router->set404(function () {
        header($_SERVER['SERVER_PROTOCOL'] . ' 404 Not Found');
        echo '404, route not found!';
    });
```

Just for asking.

Also is `$_REQUEST`, not `$_request`. It's case sensitive.

A proper way would be using something like:

```php
file_get_contents("php://input");
```

Instead of `$_REQUEST`.

Read more: https://stackoverflow.com/questions/8893574/php-php-input-vs-post

**Comment by ovflowd** [comment]
I would truly recommend you learn a little bit more of php, by reading their documentation.

But anyways, we're here to help you 😄

**Comment by abmmhasan** [comment]
I know about the case sensitive fact! I was manually writing it in some places! that is why case got in way!

**Comment by ovflowd** [comment]
Oh I see, sorry for my misunderstood. But anyways, give a check in the `php://input`

The `$_POST` and `$_REQUEST` have nothing to do with the router itself.

**Comment by abmmhasan** [comment]
thanks but the script itself now started to work! I think it was not about my code but the sync problem earlier. The code was not updating on server.

**Comment by ovflowd** [comment]
So you solved your problem? That's amazing! You can close this issue if you want :)
