### ISSUE TITLE
Adding Sanitize and Validation

### ISSUE THREAD

**Issue by abmmhasan** [bramus/router#68]
Can we add those 2 things direct into the Router; I think it will be good.
```
public static function validate($input, $filter = false)   {
		if($filter=='boolean')$variable = filter_var($input, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE);
		elseif($filter=='email')$variable = filter_var($input, FILTER_VALIDATE_EMAIL, FILTER_NULL_ON_FAILURE);
		elseif($filter=='float')$variable = filter_var($input, FILTER_VALIDATE_FLOAT, FILTER_NULL_ON_FAILURE);
		elseif($filter=='int')$variable = filter_var($input, FILTER_VALIDATE_INT, FILTER_NULL_ON_FAILURE);
		elseif($filter=='ip')$variable = filter_var($input, FILTER_VALIDATE_IP, FILTER_NULL_ON_FAILURE);
		elseif($filter=='regexp')$variable = filter_var($input, FILTER_VALIDATE_REGEXP, FILTER_NULL_ON_FAILURE);
		elseif($filter=='url')$variable = filter_var($input, FILTER_VALIDATE_URL, FILTER_NULL_ON_FAILURE);
		else $variable = filter_var($input);
		return $variable;
    }
public static function sanitize($input, $filter = false) {
		if($filter=='email')$variable = filter_var($input, FILTER_SANITIZE_EMAIL);
		elseif($filter=='encoded')$variable = filter_var($input, FILTER_SANITIZE_ENCODED);
		elseif($filter=='magic_quotes')$variable = filter_var($input, FILTER_SANITIZE_MAGIC_QUOTES);
		elseif($filter=='float')$variable = filter_var($input, FILTER_SANITIZE_NUMBER_FLOAT);
		elseif($filter=='int')$variable = filter_var($input, FILTER_SANITIZE_NUMBER_INT);
		elseif($filter=='special')$variable = filter_var($input, FILTER_SANITIZE_SPECIAL_CHARS);
		elseif($filter=='full_special')$variable = filter_var($input, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
		elseif($filter=='string')$variable = filter_var($input, FILTER_SANITIZE_STRING);
		elseif($filter=='url')$variable = filter_var($input, FILTER_SANITIZE_URL);
		else $variable = filter_var($input);
		return $variable;
    } 
```

**Comment by ovflowd** [comment]
Hey thanks for the suggestion. But why you think it would be useful? I mean, those functions are cool and have a purpose. But I think they doesn't match the purpose of this library.

Since this is just a route, it means to just route given requested into respective handlers. And just that...

But maybe I'm wrong xD

**Comment by bramus** [comment]
Hi @abmmhasan,

As @ovflowd mentioned validation indeed falls outside of the scope of the router. You can always compose the router in a bigger framework/structure which can contain the checks you suggested.

Regards,
Bramus!

**Comment by abmmhasan** [comment]
Well, I have been referring to following features actually:
https://github.com/klein/klein.php#api

**Comment by bramus** [comment]
I know, but that still fall outside of the scope of this library. This router only focusses on routing, not requests and responses.

In a real life scenario you'd of course augment this router with `Request` and `Response` classes. You're free to choose which one, or you can write your own to be used in tandem with this project. For client projects I've done so, and it works like a charm :)
