### ISSUE TITLE
Add all Required Error Codes

### ISSUE THREAD

**Issue by abmmhasan** [bramus/router#70]
1. 301 Moved Permanently
2. 302 Moved Temporarily
3. 400 Bad Request
4. 401 Authorization Required
5. 403 Forbidden
6. 404 Not Found (Only this is currently in the code)
7. 405 Method Not Allowed
8. 408 Request Timed Out
9. 415 Unsupported Media Type
10. 500 Internal Server Error
11. 501 Not Implemented
12. 502 Bad Gateway
13. 503 Service Unavailable
14. 504 Gateway Timeout
15. 505 HTTP Version Not Supported
Though some of them only implementable through htaccess only!

**Comment by bramus** [comment]
The responsibility of sending back HTTP status code falls outside of the context of `bramus/router`, as the latter only focusses on the routing itself.

I'd recommended to create your own `Response` class and put those status codes in there.

_(on a sidenote: the list you provided is incomplete. Check http://httpstat.us/ or http://httpstatus.es/ for a full list)_

**Comment by uvulpos** [comment]
Would be great, if you could make an example 😄

**Comment by bramus** [comment]
@uvulpos Check https://github.com/bramus/enumeration#composed-enumerations
