### ISSUE TITLE
Returning false runs controller method twice

### ISSUE THREAD

**Issue by floralsystems** [bramus/router#72]
I couldn't find anything mentioned about this in the documentation. Returning false from a controller method will cause it to be run twice. 

For example, this route:
```php
$router->get('/account', '\Controller\Test@method');
```
With this class:
```php
Class Test {
    function method(){
        echo 'hello';
        return false;
    }
}
```
Will produce the output: hellohello

The reason for this is line #391:
https://github.com/bramus/router/blob/master/src/Bramus/Router/Router.php#L391

PHP's "call_user_func_array" returns the return value of the callback or FALSE on error.

**Comment by bramus** [comment]
Fixed now #120 has been merged
