### ISSUE TITLE
Subfolder Detection not working properly

### ISSUE THREAD

**Issue by PlanetGamingGG** [bramus/router#82]
Hi, I've installed this library thru Composer and it has been successfully loaded.
I used the following code:
```php
/**
 * Routing System
 * @package bramus/router
 */
$router = new \Bramus\Router\Router;

$router->get('/', function() { echo "INDEX!<br>"; });
$router->get('/test', function() { echo "HI<br>"; });
$router->get('/hello', function() { echo "HELLO!!<br>"; });

$router->run();

echo "Done!";
```
But no matter what my GET request is (to `/`, `/test`, `/hello` or even `/asdf`), it always shows "INDEX!"...
Even copied and pasted the example (demo) code does not help at all! It just shows `<h1>bramus/router</h1><...`.

**Comment by hozzaq** [comment]
what about the .htaccess?

**Comment by PlanetGamingGG** [comment]
This is my .htaccess
```
# Core
Options -Indexes
Options -MultiViews
Options +FollowSymlinks
AddDefaultCharset UTF-8
ServerSignature Off
FileETag none
RewriteEngine on
RewriteBase /

# Authentication
RewriteRule ^auth/?$ /sys-auth/handler.php [NC,L]
RewriteRule ^auth/(.*)?$ /sys-auth/handler.php [NC,L]

# Assets
RewriteRule ^assets/(.*)?$ /public/assets/$1 [NC,L]

# Router
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ /public/index.php [NC,L]
```
Note: The routing was placed on `/app/initialize.php`

**Comment by bramus** [comment]
By the looks of it, am I correct to assume that your `.htaccess` not in `/public`? Seems odd _(but that as a sidenote)_.

Now, to the point:`bramus/router` should work when having your handling script placed into a subfolder, it has [extra code](https://github.com/bramus/router/blob/ae0db20708e17708c8135251b8fa34bf2a6c5f96/src/Bramus/Router/Router.php#L423) to achieve just that. Apparently it's failing with your folder structure.

To help solve this, can you do one of both:

1. Temporarily adjust `vendor/bramus/router/src/Bramus/Router/Router.php` and have it output the results for `$_SERVER['SCRIPT_NAME']`, `__DIR__`, the `getBasePath()` call, and the `getCurrentUri()` call. Then post the results here.
2. Provide a mini-repo that reproduces the folder-structure you are using with a small testrouter instance in it?

BTW: Which version of `bramus/router` are you using?

Thanks.

**Comment by PlanetGamingGG** [comment]
Hi @bramus ,
Yes my `.htaccess` is not in `/public` but it is on root.
According to my `composer.json`, I'm using version `1.4`.

For the #1 solution, 
I've modified the `getCurrentUri()` function to:
```
/**
 * Define the current relative URI.
 *
 * @return string
 */
protected function getCurrentUri()
{
    // Get the current Request URI and remove rewrite base path from it (= allows one to run the router in a sub folder)
    $uri = substr($_SERVER['REQUEST_URI'], strlen($this->getBasePath()));

    // Don't take query params into account on the URL
    if (strstr($uri, '?')) {
        $uri = substr($uri, 0, strpos($uri, '?'));
    }

    // Remove trailing slash + enforce a slash at the start
    var_dump($_SERVER['SCRIPT_NAME']);
    var_dump(__DIR__);
    var_dump($this->getBasePath());
    var_dump('/'.trim($uri, '/'));
    return '/'.trim($uri, '/');
}
```
Which outputs:
![image](https://user-images.githubusercontent.com/35788716/53234192-93eece80-36c1-11e9-9420-3f8029435024.png)
`$_SERVER['SCRIPT_NAME']` = `/public/index.php`  
`__DIR__` = `D:\wamp64\www\github\PHP-FirePower-Framework\vendor\bramus\router\src\Bramus\Router`
`getBasePath()` = `/public/`  
`getCurrentUri()` = `/`

**Comment by bramus** [comment]
OK, `getCurrentUri()` seems to return the correct result … so your folder structure does not seem to be the culprit here.

What's the output when you visit the `/hello` route you defined?

**Comment by PlanetGamingGG** [comment]
Accessing `/hello` outputs (without the debug):
```
INDEX!
Done!
```
Code:
```$router = new Router;

$router->get('/', function() { echo "INDEX!<br>"; });
$router->get('/test', function() { echo "HI<br>"; });
$router->get('/hello', function() { echo "HELLO!!<br>"; });

$router->run();

echo "Done!";```

Output with debug:
```
`SCRIPT NAME`: `/public/index.php`
`__DIR__`: `D:\wamp64\www\github\PHP-FirePower-Framework\vendor\bramus\router\src\Bramus\Router`
`getBasePath()`: `/public/`
`getCurrentUri()`: `/`
INDEX!
Done!
```

Note: I've changed the debug code to:
```php
/**
 * Define the current relative URI.
 *
 * @return string
 */
protected function getCurrentUri()
{
    // Get the current Request URI and remove rewrite base path from it (= allows one to run the router in a sub folder)
    $uri = substr($_SERVER['REQUEST_URI'], strlen($this->getBasePath()));

    // Don't take query params into account on the URL
    if (strstr($uri, '?')) {
        $uri = substr($uri, 0, strpos($uri, '?'));
    }

    // Remove trailing slash + enforce a slash at the start
    echo "`SCRIPT NAME`: `{$_SERVER['SCRIPT_NAME']}`".PHP_EOL;
    $dir = __DIR__;
    echo "`__DIR__`: `{$dir}`".PHP_EOL;
    echo "`getBasePath()`: `{$this->getBasePath()}`".PHP_EOL;
    $result = '/'.trim($uri, '/');
    echo "`getCurrentUri()`: `{$result}`".PHP_EOL;
    return '/'.trim($uri, '/');
}
```

**Comment by bramus** [comment]
What's the value for `$_SERVER['REQUEST_URI']` in that last `/hello` call?

**Comment by PlanetGamingGG** [comment]
Ah... you didn't request for REQUEST_URI previously 😅 
Here's the result when accessing `/`:
`SCRIPT NAME`: `/public/index.php`
`REQUEST URI`: `/`
`__DIR__`: `D:\wamp64\www\github\PHP-FirePower-Framework\vendor\bramus\router\src\Bramus\Router`
`getBasePath()`: `/public/`
`getCurrentUri()`: `/`

And here it is when accessing `/hello`:
`SCRIPT NAME`: `/public/index.php`
`REQUEST URI`: `/hello`
`__DIR__`: `D:\wamp64\www\github\PHP-FirePower-Framework\vendor\bramus\router\src\Bramus\Router`
`getBasePath()`: `/public/`
`getCurrentUri()`: `/`

**Comment by PlanetGamingGG** [comment]
I did some quick testing:
```
/**
 * Define the current relative URI.
 *
 * @return string
 */
protected function getCurrentUri()
{
    // Get the current Request URI and remove rewrite base path from it (= allows one to run the router in a sub folder)
    $uri = substr($_SERVER['REQUEST_URI'], strlen($this->getBasePath()));
    var_dump($uri);
    var_dump($this->getBasePath());
    var_dump($_SERVER['REQUEST_URI']);

    // Don't take query params into account on the URL
    if (strstr($uri, '?')) {
        $uri = substr($uri, 0, strpos($uri, '?'));
    }
    var_dump($uri);
    var_dump('/'.trim($uri, '/'));
    die;

    // Remove trailing slash + enforce a slash at the start
    echo "`SCRIPT NAME`: `{$_SERVER['SCRIPT_NAME']}`".PHP_EOL;
    echo "`REQUEST URI`: `{$_SERVER['REQUEST_URI']}`".PHP_EOL;
    $dir = __DIR__;
    echo "`__DIR__`: `{$dir}`".PHP_EOL;
    echo "`getBasePath()`: `{$this->getBasePath()}`".PHP_EOL;
    $result = '/'.trim($uri, '/');
    echo "`getCurrentUri()`: `{$result}`".PHP_EOL;
    return '/'.trim($uri, '/');
}
```
`$uri` returns `false` which according to the PHP docs, means there is an error.  
The error was caused by:
Since the `REQUEST_URI` is `/` which is 1 character, and `getBasePath()` is `/public/` which is 8 character and `1 - 8 = -7`, an error occured.

**Comment by PlanetGamingGG** [comment]
What are the base path for? Is it for the routing to work after a specific path?
I assume if I set the base path to `/app/` and access this:
`/test` Won't be routed
`/app/something` Routed to Something
`/app/else` Routed to Else.

This was the case if I access `/public/test`, it shows `HI` as expected. `/public/hello` shows `HELLO!!`

**Comment by PlanetGamingGG** [comment]
I've done some fixing, check my fork at https://github.com/PlanetGamingGG/router.
Will create a PR later.

**Comment by PlanetGamingGG** [comment]
After title rename:
The attempt to detect subfolder is a good feature indeed but I think it is too aggressive and should be optional. If you wanted to keep the subfolder detection system, please let me know so I can implement it @bramus

**Comment by bramus** [comment]
Thinking over this issue during the weekend, I had an epiphany about this issue _(after all, it's been over six years that this feature was created)_: the subfolder feature was originally created to make `bramus/router` work when being run from a subfolder.

This way you can place your code (`index.php` + `.htaccess`) in your webserver's root (mostly `www` or `public_html`) or any subfolder thereof:

- Place your code in `public_html` and your routes will be mounted from the domain `www.example.org` itself.
- Place your code in `public_html/demo/router/movies/` and your routes will be mounted from the URL `www.example.org/demo/router/movies/`.

To achieve this, some "magic" happens in  `getCurrentUri()` and `getBasePath()`: it removes the basepath of the entry script (`$_SERVER['SCRIPT_NAME']`) from the entry URL (`$_SERVER['REQUEST_URI']`).

What you are having here is somewhat similar, yet quite different from it: your entry URLs are at the domain level `www.example.org`, yet your entry script lives at `www.example.org/public/` _(e.g. your entry script and your entry URLs are not tightly coupled)_. In that case the "magic" inside `getCurrentUri()` and `getBasePath()` will fail of course, as that wasn't the intended use case.

The true proper fix for your use case is a simple addition of a `setBasePath()` function, which you should call after initializing your router:

```php
$router = new \Bramus\Router\Router;

// Override auto base path detection, to play nice with 
$router->setBasePath('/');

$router->get('/', function() { echo "INDEX!<br>"; });
$router->get('/test', function() { echo "HI<br>"; });
$router->get('/hello', function() { echo "HELLO!!<br>"; });

$router->run();

echo "Done!";
```

By adding this functionality:
- Backwards compatibility is maintained, and the intended subfolder use cases will still work out of the box.
- Your use case will work.

I'm about to push some changes that add this, and which should fix your issue. When tested and verified by you I'll release this as a new version.
