### ISSUE TITLE
Expect to be able to customize URL which will be used to match

### ISSUE THREAD

**Issue by DFFZMXJ** [bramus/router#85]
I have my own method to get the path info:
```php
<?php
const __PATH_INFO__ = $_SERVER['PATH_INFO']??$_SERVER['REDIRECT_PATH_INFO']??$_SERVER['REDIRECT_URL']??'/path-info-unsupported';
```
But there are no interfaces to apply this. I have to change your router system's source code:
```php
    /**
     * Define the current relative URI.
     *
     * @return string
     */
    protected function getCurrentUri()
    {
        return \__PATH_INFO__;//Customized path info.
        // Get the current Request URI and remove rewrite base path from it (= allows one to run the router in a sub folder)
        $uri = substr($_SERVER['REQUEST_URI'], strlen($this->getBasePath()));
        // Don't take query params into account on the URL
        if (strstr($uri, '?')) {
            $uri = substr($uri, 0, strpos($uri, '?'));
        }
        // Remove trailing slash + enforce a slash at the start
        return '/'.trim($uri, '/');
    }
```
So how about adding an interface to add a custom URL?

**Comment by bramus** [comment]
Can't quite follow here I must say. Can you elaborate on this? Use cases? Example scenarios? etc.

**Comment by DFFZMXJ** [comment]
Your program uses `REQUEST_URI` by default. For most people that's enough because they only setup their programs at the root path. (Relative to URL) **But what if I execute the file at a sub-directory?**

I am not good at English, maybe you don't understand that.

e.g. A PHP file has been stored at `/a-directory/index.php` (Relative to URL) 

When I try to access this file, normally, I will access `/a-directory/any-routes` (With .htaccess setting in `/a-directory`), and the program must identify it automatically.

So I must add these code:

```php
<?php
$sub_directory = '/a-directory';//Should be in database, but here is for example.
$router->mount($sub_directory, function() use ($router) {
    $router->get('/any-routes', function() {
        echo 'something';
    });
);
```

Which means I have to store extra data, that's troubled.

If I use `PATH_INFO`, I will no longer need to store the extra data.

```php
<?php
//Assume your program has used PATH_INFO and the user has accessed /a-directory/index.php/any-routes (Without .htaccess setting) or /a-directory/any-routes (With .htaccess setting)
$router->get('/any-routes',function() {
    echo 'something';
});
```

But not everyone wanted `PATH_INFO` and not everyone wanted `REQUEST_URL`.

Did you see the worth to allow users to provide a custom URL without modifying source code?

**Comment by DFFZMXJ** [comment]
To make your program support this method, there may be one possible rapid version to realize.
```php
<?php
class enhancedRouter extends Bramus\Router\Router{
    private $url = null;
    protected function getCurrentUri(){
        if($this->url) return $this->url;
        //Continue your method.
    }
    public function setURL($url=null){
        if($url) $this->url = $url; //Or remove the condition to allow to reset.
    }
}
```

In my opinion, it will not lose performance.

**Comment by bramus** [comment]
Ah, think I got it: you're having an issue when running `bramus/router` in a subfolder.

Here's the good news: `bramus/router` can work in subfolders out-of-the-box … no adjustments in your code are needed: you can move your `index.php` file around freely and the router will still work (relatively from that new path/URL).

Say you have a router `public_html/a-directory/index.php`, then the code below will respond to `www.example.org/a-directory/any-routes/`:

```php
$router->get('/any-routes', function() {
        echo 'something';
});
```
There's **no** need for `$router->mount(…)` in this case.

~

For example, I've added uploaded a router implementation to https://www.bram.us/demo/projects/php-router/. It's source file is `/www/demo/projects/php-router/index.php`, and this is the code:

```php
<?php

    require __DIR__ . '/../../../../vendor/autoload.php';

    class Handler {
        public static function index() {
            echo 'Yo!' . PHP_EOL;
        }
        public static function notfound() {
            header('HTTP/1.1 404 Not Found');
            echo 'UH OH …' . PHP_EOL;
        }
    }

    $router = new \Bramus\Router\Router();

    $router->set404('Handler@notfound');

    $router->get('/', 'Handler@index');
    $router->get('/hello/([A-z0-9\.]+)', function($name) {
        echo 'Hello ' . htmlentities($name);
    });

    $router->run();

// EOF
```

If I where to publish this to another subdirectory, then it would still work.

Here's the `.htaccess` (`/www/demo/projects/php-router/.htaccess`) that goes along with that:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php [L]
```

~

If I have mis-understood your issue, feel free to leave a reply and I'll gladly reopen.
