### ISSUE TITLE
load custome page

### ISSUE THREAD

**Issue by asadghazanfary** [bramus/router#89]
how can i load custom page with optional parameters?

for example:

/

or

/[page/1,2,..]

**Comment by WeaponsTheyFear** [comment]
$router->get('/hello/(\w+)', function($name) {
    echo 'Hello ' . htmlentities($name);
});

Right from the readme.  Is this what you are asking, the question isn't very detailed?  In place of echoing, you could call a controller/method or a number of other options.

**Comment by asadghazanfary** [comment]
i want load custom php page in function section and load custom page with different page number

**Comment by WeaponsTheyFear** [comment]
commented 24 minutes ago
$router->get('/page/(\d+)', function($id) {
    // require script here, call your_func ( $id);
});

This would represent yoursite.com/page/12 (or any digits).  You can require your script there and call a function, passing $id to that function.

**Comment by ovflowd** [comment]
I'm sorry to say, but this isn't an Issue from the library, but a misguidance of yourself. The documentation explains exactly what you need to do.

Here is not the place to ask this kind of questions. I'm sure you will get the proper support in Stackoverflow.

I don't want to be rude, but this Issue isn't an Issue of the Router. Still, @weaponstheyfear explained exactly your questions :)

Hope you understand 😁
