### ISSUE TITLE
The Matching Problem After Mount

### ISSUE THREAD

**Issue by chenbaba** [bramus/router#90]
If I refactored the getCurrentUri method, then all my get post requests could go according to the refactoring, then why after I changed to mount, the method I defined would no longer work and would never match. I don't know how to explain this situation, but hopefully it's my question. I need a more professional answer or a more interesting idea.

**Comment by bramus** [comment]
When things go wrong after tinkering with the internals of the router, then I cannot really help you out. Since it works as intended _(without modifying)_, I'm labeling this as invalid.

**Comment by chenbaba** [comment]
I think this package is very light, and then I add a dependency injection to you, but I don't have an adapter container, because I want the people behind me to maintain it. I'll paste the code up for you, you see, because it's just written, and then if there's a problem, I want you to give me more advice, which brings you a small requirement, that is, I want my routing to be specified by a parameter, not by a parameter. Whole URI







`    private function invoke($fn, $params = [])
    {
        if (is_callable($fn)) {
            call_user_func_array($fn, $params);
        }

        // If not, check the existence of special parameters
        elseif (stripos($fn, '@') !== false) {
            // Explode segments of given route
            list($controller, $method) = explode('@', $fn);
            $this->method = $method;
            // Adjust controller class if namespace has been set
            if ($this->getNamespace() !== '') {
                $controller = $this->getNamespace() . '\\' . $controller;
            }
            // Check if class exists, if not just ignore and check if the class exists on the default namespace
            if (class_exists($controller)) {
                //获取依赖注入
                return $this->make($controller,$params);

                // First check if is a static method, directly trying to invoke it.
                // If isn't a valid static method, we will try as a normal method invocation.
//                if (call_user_func_array([new $controller(), $method], $params) === false) {
//                    // Try to call the method as an non-static method. (the if does nothing, only avoids the notice)
//                    if (forward_static_call_array([$controller, $method], $params) === false);
//                }
            }
        }
    }


    public function make($controller,$params)
    {

        $instance = (new \ReflectionClass($controller))->newInstance();
        $reflectionMethod = new \ReflectionMethod($controller,$this->method);
        $parameters = $reflectionMethod->getParameters();

        if (empty($parameters)) {
            return $reflectionMethod->invoke($instance);
        } else {
            $args = [];
            foreach ($parameters as $parameterObj) {
                if ($reflectionclass = $parameterObj->getClass()) {
                    $className = $reflectionclass->getName();
                    $args[] = (new \ReflectionClass($className))->newInstance();
                } else {
                    $args[] = 'hello';
                }
            }
            $args = array_merge($args,$params);

            return $reflectionMethod->invoke($instance, ...$args);
        }
    }`

**Comment by chenbaba** [comment]
I've solved it and achieved what I wanted. Thank you. This bag is really great!

**Comment by bramus** [comment]
Could you share your solution? And/or is it PR-worthy?

**Comment by chenbaba** [comment]
of course , but I'll sort it out. I'm going to share it with you and write a test for you.
