### ISSUE TITLE
Problem with dynamic routes and mount

### ISSUE THREAD

**Issue by iKevinShah** [bramus/router#93]
Hi, 

I tried searching but I did not get the issue / solution. Not sure if this is reported. Here is the problem I am facing, I am creating a reddit sort of url scheme.

URL Structure needed: 

```

/ -> Homepage
/{category_url}/ -> show category posts
/{category_url}/view/{post_url} -> show post within category.


```

I can do that in multiple routes but I am trying to use subrouting / Mounting Routes: 

Here is the code: 

```

$router->mount('/{category_url}', function($category_url) use ($router) {

    $router->get('/', function() use($category_url) {
        echo "Show Category: ".$category_url;
    });

    $router->get('/view/{post_url}', function($post_url) use($category_url) {
        echo "Show post: ".$post_url." in category" .$category_url;
    });

});

```

even this is not working: 
```
$router->get('/{category_url}',function($category_url){
    echo "Show Category: ".$category_url;
});

$router->get('/{category_url}/view/{post_url}', function($category_url, $post_url) use($router) {
    echo "Show post: ".$post_url." in category" .$category_url;
});


```

I feel I am doing something wrong rather than this being an "issue" with the router. However, clarification from the community would be great.

**Comment by iKevinShah** [comment]
Hi guys, 

Anyone could help me with this or can guide me if I am doing it wrong?

**Comment by ovflowd** [comment]
Hey @iKevinShah that's a very strange behaviour.

Did you run `$router->run();` ?

**Comment by ovflowd** [comment]
PS: Remember that PCRE's are `(*)` wildcards.

So depending `/` can be interpreted as the same as `{category_url}`

**Comment by ovflowd** [comment]
Try:

```
$router->mount('/posts/{category_url}', function($category_url) use ($router) {
    $router->get('/', function() use($category_url) {
        echo "Show Category: ".$category_url;
    });

    $router->get('/view/{post_url}', function($post_url) use($category_url) {
        echo "Show post: ".$post_url." in category" .$category_url;
    });
});
```

**Comment by iKevinShah** [comment]
> $router->mount('/posts/{category_url}', function($category_url) use ($router) {
>     $router->get('/', function() use($category_url) {
>         echo "Show Category: ".$category_url;
>     });
> 
>     $router->get('/view/{post_url}', function($post_url) use($category_url) {
>         echo "Show post: ".$post_url." in category" .$category_url;
>     });
> });

Error: Too few arguments to function {closure}(), 0 passed and exactly 1 expected.
Error on: line `$router->mount('/posts/{category_url}', function($category_url) use ($router) {`

**Comment by ovflowd** [comment]
Well something weird is happening, because it should be working.

**Comment by iKevinShah** [comment]
I feel the same :/

**Comment by bramus** [comment]
With error reporting enabled you can see an error be generated:

```
Uncaught ArgumentCountError: Too few arguments to function {closure}(), 0 passed and exactly 1 expected in /Users/bramus/repos/tests/router/index.php:11 Stack trace: #0 [internal function]: {closure}() #1 /Users/bramus/repos/tests/router/vendor/bramus/router/src/Bramus/Router/Router.php(182): call_user_func(Object(Closure)) #2 /Users/bramus/repos/tests/router/index.php(23): Bramus\Router\Router->mount('/{category_url}...', Object(Closure)) #3 {main} thrown in /Users/bramus/repos/tests/router/index.php on line 11
```

Checking the source of the [the `mount()` function](https://github.com/bramus/router/blob/master/src/Bramus/Router/Router.php#L173) you can see that it calls its handling function without any arguments. The `$category_url` that you use does not get injected into the callable.

How does it work then? Well, the `mount()` function is designed to mount all contained routes onto its given `$baseRoute` **by prefixen that `$baseRoute` onto all route handlers defined inside of it**. The instruction `$router->get('/view/{post_url}'` (inside `$router->mount('/{category_url}'`) will thus be translated to as `$router->get('/{category_url}/view/{post_url}`. It's that handling function that will get both parameters (`$category_url` and `$post_url`) directly injected.

Can't quite follow? No worries, here's the adjusted code that does the job:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

$router = new \Bramus\Router\Router();

$router->mount('/{category_url}', function() use ($router) {

    $router->get('/', function($category_url) {
        echo "Show Category: ".$category_url;
    });

    $router->get('/view/{post_url}', function ($category_url, $post_url) {
        echo "Show post: ".$post_url." in category" .$category_url;
    });

});

$router->run();
```

**Comment by iKevinShah** [comment]
@bramus , your explanation is good, detailed. Liked it.

However, when I ran that, only the `echo "Show Category: ".$category_url;` is shown.

So I moved that bit to the end, that should be ok right?
```


// Create Router instance
$router = new \Bramus\Router\Router();

// Define routes
$router->mount('/{category_url}', function() use ($router) {

    $router->get('/view/{post_url}/', function ($category_url, $post_url) {
        echo "Show post: ".$post_url." in category " .$category_url;
    });

    $router->get('/', function($category_url) {
        echo "Show Category: ".$category_url;
    });


});


// Run the router!
$router->run();

```

**Comment by bramus** [comment]
Good catch, @iKevinShah!
