### ISSUE TITLE
Does bramus/router support REST routing

### ISSUE THREAD

**Issue by kezenwa** [bramus/router#94]
Am sorry for opening a new thread just for a question like this BUT i see no where else to ask that neither do I see it mentioned anywhere else.

Does bramus/router support REST routing ?

Thanks

**Comment by necmettin** [comment]
What does REST routing mean? You can create any route you wish with bramus/router.

If you wish something like replicating

```
/users/{id}
/groups/{id}
```

you can easily achieve that with creating a single route like `/{plural}/{id}` and performing permission checks on the `$plural` object. You can also easily replicate other REST routes with similar logic.

**Comment by bramus** [comment]
‘bramus/router’ is a router that works on the HTTP level. REST is a layer on top of HTTP. 

How you use ‘bramus/router’ is up to you. You can use it to implement REST, XML RPC, etc.

Do note that ‘bramus/router’ is a library/component, not a framework. You don’t get REST out of the box with it, but you can use it to build your own implementation.

**Comment by kezenwa** [comment]
Thanks for your response. Asked as I was considering choosing between this and some others BUT your response cleared the Air.
Now am sure i would be going with this Router.

Additionally, need to ask this also

Is it possible to compile all routes as an array in a different file and load it to this router.

Similar to how CodeIgniter does theirs in routes.php e.g

$route['default_controller'] = 'welcome';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;
$route['(?i)livescores'] = 'welcome/livescore';
$route['(?i)livescore'] = 'welcome/livescore';
$route['(?i)live'] = 'welcome/livescore';
$route['(?i)about'] = 'welcome/about';
$route['(?i)contact'] = 'welcome/contact';
$route['(?i)results'] = 'Results/index';
$route['(?i)week'] = 'Results/index';

which later is loader to the router class when initialized.

Already looking to modify and/ or extend your class into doing same BUT wants to be 100% sure it's not already implemented and i missed it.

reason is, I want to migrate my router class to bramus/router and trying to avoid cluttering the controller files with multiple $router->get(),  $router->match(), etc.

Thanks
