### ISSUE TITLE
How to access Parameters from route

### ISSUE THREAD

**Issue by kezenwa** [bramus/router#95]
Am kinda lost even after going through the examples and description page multiple times.

If I have a url in this format -> http://example.com/properties/for-sale/canada/condo/3-bed-room-duplex.
I can easily route the above url to the correct controller which would match the request uri and display the page for  http://example.com/properties/for-sale/canada/condo/3-bed-room-duplex    BUT how do i extract these parameters   'for-sale', 'canada', 'condo', '3-bed-room-duplex'

Let's assume I used the $router->get() function.

Have gone through the codes and can see where the parameters called ₦params  exists but without having to modify the class, need to know if I already can access those values without knowing.

This is to avoid modifying a code whose function I want to implement already exists.

Thanks

**Comment by kezenwa** [comment]
At the moment, a url in this format  http://example.com/properties/for-sale/canada/condo/3-bed-room-duplex gets routed correctly BUT not having access to those parameters means I can't perform certain advanced processing via mysql.

**Comment by WeaponsTheyFear** [comment]
It gets routed correctly, can you paste the route you are using?

**Comment by kezenwa** [comment]
$router->get (/properties/listings/(.*),  'propertyController@singleDetail') correctly routes the url http://example.com/properties/listings/for-sale/canada/condo/3-bed-room-duplex and it displays.

BUT on that view page, i need to do some processings such as display related properties based on certain criteria e.g location, property type, etc and those conditions should be similar to currently viewed property hence i need a way to get parameters from the url e.g 'for-sale', 'canada', 'condo', '3-bed-room-duplex'

so that i can use them to query the database. Please nothe that the parameters 'for-sale', 'canada', 'condo', '3-bed-room-duplex' will always change based on the url .

I know I can easily use explode() function to split $_SERVER['REQUEST_URI'] and grab those variables BUT that would be hacky hence I want to know if bramus/router already implements such feature.

Have plans to modify the bramus/router class BUT need to be sure the feature doesn't already exists.

Hope am clear enough.

Thanks

**Comment by kezenwa** [comment]
> It gets routed correctly, can you paste the route you are using? What is in () or {} in your expression should become a parameter. For example, a route that matches anything $router->get ('/(.*) ') will give you the entire url as a parameter. I'd assume in your example you'd be after 'canada', 'condo', and 3-bed as parameters?
> 
> $router->get('/profile/(\w+)/(\w+)/([a-z0-9_-]+)
> 
> You'd end up with canada, condo, and anything that was alpha, digit, _ or -. The problem with this route is that if you only had canada/condo the route would not match. I'm not the greatest with regex at all (in fact, I suck with them), but there is probably a optional match pattern that would take care of this. Otherwise you could do as I did with one of my routes (I used a controller, index type of method):
> 
> $router->get('/profile/(.*)')
> 
> This gave me the rest of the url and my controller split it and determined what to do with it. Probably cheap solution in many peoples eyes.

Yes I get what you mean BUT am after how to access the array holding all the parameters for the current request so I can use them like this

$propertyType = $params[0];
$location = $params[1];
$slug = $params[2];

this way, I can now use them in querying mysql database to get related properties.

Like already said, the Request gets routed correctly BUT i need access to the parameters

**Comment by WeaponsTheyFear** [comment]
In your route above, the rest of the url match should be a single parameter (it should be canada/condo/whatever).

Try func_get_args and see what it says.  From there, you can always explode that to get each piece to process.

**Comment by kezenwa** [comment]
Sorry BUT i need to point something out

If I were to use the function like below 

$router->get('/movies/(\d+)/photos/(\d+)', function($movieId, $photoId) {
    echo 'Movie #' . $movieId . ', photo #' . $photoId);
});

It would work BUT am using something similar to below

$router->get('/properties/(\d+)/listings/(\d+)', 'PropertyController@PropertyDetail');
This means I have a class named PropertyController with a method called PropertyDetail defined somewhere.

Now after calling $router->run in my index.php, the correct controller gets called and run BUT now if I need to have access to parameters from the url e.g  'canada',  '3-bed as parameters', was thinking bramus/router would already have a method that i can call like $params = $router->params() that would return those parameters like below


$propertyType = $params[0];
$slug = $params[2];


Well since such doesn't currently exist, I would have to implement it by modifying the class so as to avoid having to constantly call explode() to split $_SERVER[REQUEST_URI] for me.

Thanks

**Comment by WeaponsTheyFear** [comment]
I use that method as well.  All it does is use the controller and method in call_user_func and passes any params to it.  In your controller method, try fu ction propertyDetail ($url) and echo $url.  It passes the params to your controller and method.

**Comment by bramus** [comment]
Please read the provided documentation thoroughly, especially [the section on route patterns](https://github.com/bramus/router/blob/master/README.md#dynamic-pcre-based-route-patterns)

> The **subpatterns** defined in Dynamic PCRE-based Route Patterns are converted to parameters which are passed into the route handling function.

The example following that section details how parameters are injected into the callback function:

```
$router->get('/hello/(\w+)', function($name) {
    echo 'Hello ' . htmlentities($name);
});
```

So no need for `func_get_args`, the defined route params get injected into the callback function itself. 

This is also applicable to [`Class@method` calls](https://github.com/bramus/router/blob/master/README.md#classmethod-calls)

**Comment by jdcw1998** [comment]
hello would someone be able to explain a bit further because i am also wondering how to get var from the url in a view i am also using Class@Method as i cant seem to figure out how so for example /profile/foobar i want to get foobar in the view, sorry i havent been using mvc for long so still learning thanks jimmy

**Comment by cristhunberg** [comment]
hello@jdcw1998 your can pass the arguments in your method to access. if your routes like /user/(\d+)/\(d+) then you can access these parameters like
class user {
function index($a, $b) {
echo $a . $b;
}

where (\d+) = $a
and another (\d+) == $b
