### ISSUE TITLE
Cross-site scripting issue in multilang demo

### ISSUE THREAD

**Issue by csmith** [bramus/router#96]
The [mutli-language demo](https://github.com/bramus/router/blob/master/demo-multilang/index.php) has a cross-site scripting vulnerability in the slug.

e.g. a request to `/nl/test<script>alert()</script>` results in the following HTML:

```html
This is the nl version of test<script>alert()</script> (multiple segments allowed)
```

and obvious displays an alert box:

![image](https://user-images.githubusercontent.com/189133/59970351-b9022980-955b-11e9-8f92-72aa16d655dc.png)

This is in the demo code so it's not a super critical security issue, but I think there are two very good reasons to fix this:

1) As it's a demo, users may build on it and reuse it. Obviously the routes in the demo are trivial but it could end up reused in a simple error handler or something, and without the nudge to escape HTML it might be overlooked.

2) I actually came across this while poking around a vendor folder that was publicly accessible. That's bad for a whole variety of reasons, but the XSS in the demo would have been an easy access point for stealing admin credentials etc.

**Comment by leotop** [comment]
'/([a-z0-9_-]+)**(/.*)**

**Comment by bramus** [comment]
People shouldn't put the vendor folder online, but [unfortunately they do](https://www.bram.us/2020/05/12/phpunit-a-security-risk/), so I've added a commit to fix this. Thanks for reporting.
