### ISSUE TITLE
enhancement : add a route redirect

### ISSUE THREAD

**Issue by Neurozone** [bramus/router#98]
Can you add a type like $router->redirect()

like header('location: /settings');

but $router->redirect('/settings')

?

**Comment by boralp** [comment]
Redirecting can be done by 301, 302 and 307 so maybe a little more detail needed for the function.

**Comment by Neurozone** [comment]
something like 
$router->redirect($url,$httpCode)

**Comment by gabrielcarvalhogama** [comment]
I need that too :sad:

**Comment by necmettin** [comment]
what should `$router->redirect` do that `header('location:` can't? because otherwise it would just be replicating what `header('location` does..

**Comment by ovflowd** [comment]
It would be actually nice to have this as a feature, since `redirecting` is part of what a router should do. Even if is simply just copying the `header()` syntax in a properish way.

👍 for the suggestion.

**Comment by Neurozone** [comment]
> 
> 
> what should `$router->redirect` do that `header('location:` can't? because otherwise it would just be replicating what `header('location` does..

In order to output good redirection header maybe.
I'm not a professional dev, so sometimes I need more functions

**Comment by bramus** [comment]
Thanks for this request. Currently this is not in the scope of `bramus/router` as `bramus/router` only contains a `Router` class, and no `Request` nor `Response` classes. A `redirect` method would be something typically for a `Response` class to hold, not a `Router` class.

You can write your own `Response` and `Request` classes (or use those from other libraries) that have this functionality, or use PHP's built-in `header` function a suggested by other commenters here.
