### ISSUE TITLE
[enhancement/feature request]: route priority

### ISSUE THREAD

**Issue by bassauer-storms-media** [bramus/router#99]
In principle the topic title says it all:

Could we have the possibility to set route priority so that we can define in which order routes that both match in some cases are processed? 

It would also come in handy if then a route could prevent another route that would also match from being executed.

**Comment by necmettin** [comment]
Isn't it more logical to put the behavior in difference into the handler rather than the router? Can you provide an example where you can't get away with a simple `if` and you would have to define two handlers for the same route?

**Comment by boralp** [comment]
It may not be a good idea since very popular CSS z-index property ends up like z-index: 99999. How one can be sure the router file will not be a spaghetti...

**Comment by bramus** [comment]
`bramus/router` only executes one matched route. The first one that matches will be execute. This way the order you define your route handling callbacks in, also defines the priority.
